#!/bin/bash

DEFAULT_SRC_USER="pi"
DEFAULT_SRC_HOST="cortex.fis.ucm.es"
DEFAULT_SRC_DIR="/var/dbase"
DEFAULT_DST_DIR="/var/dbase"
DEFAULT_DATE=$(/usr/bin/date +%Y%m%d)

# Some commands
NICE=$(which nice)
IONICE=$(which ionice)
RSYNC=$(which rsync)
TESSDB_INDEX=/usr/local/bin/tessdb_index

# Arguments from the command line & default values
SRC_USER="${1:-$DEFAULT_SRC_USER}"
SRC_HOST="${2:-$DEFAULT_SRC_HOST}"
SRC_DIR="${3:-$DEFAULT_SRC_DIR}"
DST_DIR="${4:-$DEFAULT_DST_DIR}"
DATE="${5:-$DEFAULT_DATE}"

TEE=$(which tee)
LOG_DATE=$(/usr/bin/date +%Y%m%d)
LOG_FILE="${HOME}/dbase/log/ida_daily_${LOG_DATE}.log"

#getting remote backup copy
echo "getting remote file by rsync" | ${TEE} -a ${LOG_FILE}
echo "${NICE} -n 19 ${IONICE} -c3 ${RSYNC} -zavh ${SRC_USER}@${SRC_HOST}:${SRC_DIR}/tess.db-${DATE} ${DST_DIR}/tess.db" | ${TEE} -a ${LOG_FILE}
${NICE} -n 19 ${IONICE} -c3 ${RSYNC} -zavh ${SRC_USER}@${SRC_HOST}:${SRC_DIR}/tess.db-${DATE} ${DST_DIR}/tess.db | ${TEE} -a ${LOG_FILE}
