#!/bin/bash

help() {
	echo "Usage:"
	echo "$0 -u <remote user> -s <source host> -i <source dir> -o <dst dir> -m <YYYY-MM> -l <log file path prefix>"
	echo "Defaults to:"
	echo "$0 -u $DEFAULT_SRC_USER -s $DEFAULT_SRC_HOST -i $DEFAULT_SRC_DIR -o $DEFAULT_DST_DIR -m $DEFAULT_DATE -l $DEFAULT_LOG_FILE_PREFIX"
}

DEFAULT_SRC_USER="pi"
DEFAULT_SRC_HOST="cortex.fis.ucm.es"
DEFAULT_SRC_DIR="/var/dbase"
DEFAULT_DST_DIR="/var/dbase"
DEFAULT_DATE=$(/usr/bin/date +%Y%m%d)
DEFAULT_LOG_PREFIX=/var/log/ida_daily

# Some commands
NICE=$(which nice)
IONICE=$(which ionice)
RSYNC=$(which rsync)
TEE=$(which tee)

# Arguments from the command line & default values
src_user="${DEFAULT_SRC_USER}"
src_host="${DEFAULT_SRC_HOST}"
src_dir="${DEFAULT_SRC_DIR}"
dst_dir="${DEFAULT_DST_DIR}"
date="${DEFAULT_DATE}"
log_file="${DEFAULT_LOG_FILE_PREFIX}_${DEFAULT_DATE}.log"


while getopts ":hu:s:i:o:m:l:" opt; do
 	case ${opt} in
   	u)
		src_user="${OPTARG}"
		;;
   	s)
		src_host="${OPTARG}"
		;;
   	i)
		src_dir="${OPTARG}"
      	;;
    o)
    	dst_dir="${OPTARG}"
      	;;
    m)
     	date="${OPTARG}"
      	;;
    l)
    	log_file="${OPTARG}_${DEFAULT_DATE}.log"
      	;;
    h)
        help
        exit 0
      	;;
    :)
    	echo "Option -${OPTARG} requires an argument."
    	exit 1
      	;;
    ?)
      	echo "Invalid option: -${OPTARG}."
      	exit 1
      	;;
  esac
done
shift "$((OPTIND-1))"


#getting remote backup copy
echo "getting remote file by rsync" | ${TEE} -a ${log_file}
echo "${NICE} -n 19 ${IONICE} -c3 ${RSYNC} -zavh ${src_user}@${src_host}:${src_dir}/tess.db-${date} ${dst_dir}/tess.db" 2>&1 | ${TEE} -a ${log_file}
${NICE} -n 19 ${IONICE} -c3 ${RSYNC} -zavh ${src_user}@${src_host}:${src_dir}/tess.db-${date} ${dst_dir}/tess.db 2>&1 | ${TEE} -a ${log_file}
