#!/bin/bash
# Cumulative TESS data bulk dump since the beginning of the project in IDA format
# This is meant to be invoked manually, not a from cron file

# ------------------------------------------------------------------------------
#                             AUXILIARY FUNCTIONS
# ------------------------------------------------------------------------------

query_names() {
dbase=$1
sqlite3 ${dbase} <<EOF
SELECT name 
FROM tess_v 
WHERE name like 'stars%' 
AND valid_state = 'Current' 
ORDER by CAST(substr(name, 6) as decimal) ASC;
EOF
}

# ------------------------------------------------------------------------------- #

TESS_IDA=/usr/local/bin/tess-ida

DEFAULT_DATABASE="/var/dbase/tess.db"
DEFAULT_REPORTS_DIR="/var/dbase/reports/IDA"
DEFAULT_START_DATE="2015-01"


TEE=$(which tee)
LOG_DATE=$(/usr/bin/date +%Y%m%d)
LOG_FILE="${HOME}/dbase/log/ida_all_${LOG_DATE}.log"

# get the name from the script name without extensions
name=$(basename ${0%.sh})

# Gets the month timestamp from the command line
from_month="${1:-$DEFAULT_START_DATE}"

# Either the default or the rotated tess.db-* database
dbase="${2:-$DEFAULT_DATABASE}"
# wildcard expansion ...
dbase="$(ls -1 $dbase)"

# Output directory is created if not exists inside the inner script
out_dir="${3:-$DEFAULT_REPORTS_DIR}"


if  [[ ! -f $dbase || ! -r $dbase ]]; then
        echo "[WARNING] Database file $dbase does not exists or is not readable. Aborting..." | ${TEE} -a ${LOG_FILE}
        exit 1
fi


if  [[ -f /etc/cron.d/tessdb_remote_backup ]]; then
        echo "[WARNING] tess.db remote  backup is active. Aborting..." | ${TEE} -a ${LOG_FILE}
        exit 1
fi


if  [[ -f /etc/cron.d/webdav_ida_rclone ]]; then
        echo "[WARNING] IDA WebDAV sync is active. Aborting..." | ${TEE} -a ${LOG_FILE}
        exit 1
fi

if  [[ -d ${out_dir} ]]; then
        echo "[INFO] Purge previous IDA reports directory..." | ${TEE} -a ${LOG_FILE}
        rm -fr ${out_dir}
        mkdir -p ${out_dir}
fi

photometers=$(query_names ${dbase})
# Loops over the instruments file and dumping data
for instrument in $photometers; do
    echo "[INFO] Generating IDA file for TESS $instrument for ${START_DATE} under ${out_dir}/${instrument}" | ${TEE} -a ${LOG_FILE}
    ${TESS_IDA} ${instrument} --console --log-file ${LOG_FILE} --from-month ${from_month} -d ${dbase} -o ${out_dir}
done

echo "FINALIZED ALL BULK DUMP !!!!"
