#!/bin/bash
# This script dumps latest month readings from every TESS given in an instrument list file.

# ------------------------------------------------------------------------------
#                             AUXILIARY FUNCTIONS
# ------------------------------------------------------------------------------

query_names() {
dbase=$1
sqlite3 ${dbase} <<EOF
SELECT name 
FROM tess_v 
WHERE name like 'stars%' 
AND valid_state = 'Current' 
ORDER by CAST(substr(name, 6) as decimal) ASC;
EOF
}

# ------------------------------------------------------------------------------- #

TESS_IDA=/usr/local/bin/tess-ida

DEFAULT_DATABASE="/var/dbase/tess.db"
DEFAULT_REPORTS_DIR="/var/dbase/reports/IDA"
DEFAULT_MONTH="latest"

TEE=$(which tee)

LOG_DATE=$(/usr/bin/date +%Y%m%d)

# get the name from the script name without extensions
name=$(basename ${0%.sh})

# Either the default or the rotated tess.db-* database
dbase="${1:-$DEFAULT_DATABASE}"
# wildcard expansion ...
dbase="$(ls -1 $dbase)"

# Output directory is created if not exists inside the inner script
out_dir="${2:-$DEFAULT_REPORTS_DIR}"

# Month: either "latest", "previous" or "YYYY-MM"
month="${3:-$DEFAULT_MONTH}"


if  [[ ! -f $dbase || ! -r $dbase ]]; then
        echo "Database file $dbase does not exists or is not readable." | ${TEE} -a ${LOG_FILE}
        echo "Exiting" | ${TEE} -a ${LOG_FILE}
        exit 1
fi


photometers=$(query_names ${dbase})
# Loops over the instruments file and dumping data
for instrument in $photometers; do
    if [[ "$month" = "latest" ]];
    then
        echo "Generating latest month IDA file for TESS $instrument under ${out_dir}/${instrument}" | ${TEE} -a ${LOG_FILE}
        ${TESS_IDA} ${instrument} --log-file ${LOG_FILE} --latest-month -d ${dbase} -o ${out_dir} 
    elif [[ "$month" = "previous" ]];
    then
        LOG_FILE="${HOME}/dbase/log/ida_monthly_${LOG_DATE}.log"
        echo "Generating previous month IDA file for TESS $instrument under ${out_dir}/${instrument}" | ${TEE} -a ${LOG_FILE}
        ${TESS_IDA} ${instrument} --log-file ${LOG_FILE} --previous-month -d ${dbase} -o ${out_dir}
    else
        LOG_FILE="${HOME}/dbase/log/ida_oneoff_${LOG_DATE}.log"
        echo "Generating IDA file for TESS $instrument for month $month under ${out_dir}/${instrument}" | ${TEE} -a ${LOG_FILE}
        ${TESS_IDA} ${instrument} --log-file ${LOG_FILE} --for-month ${month} -d ${dbase} -o ${out_dir}
    fi
done

