#!/bin/bash

# This script creates indices for reports.
DEFAULT_DATABASE="/var/dbase/tess.db"

# Arguments from the command line & default values

# Either the default or the rotated tess.db-* database
dbases="${1:-$DEFAULT_DATABASE}"
# wildcard expansion for the logrotared backups ...
dbases="$(ls -1 $dbases)"

NICE=$(which nice)
IONICE=$(which ionice)
SQLITE=$(which sqlite3)
# ------------------------------------------------------------------------------
#                             AUXILIARY FUNCTIONS
# ------------------------------------------------------------------------------

create_indices() {
dbase=$1
${NICE} -n 19 ${IONICE} -c3 ${SQLITE} ${dbase} <<EOF
-- Create a covering index for locations
CREATE INDEX IF NOT EXISTS tess_readings_i ON tess_readings_t(tess_id, date_id, time_id, location_id);
CREATE INDEX IF NOT EXISTS tess_id_readings4c_i ON tess_readings4c_t(tess_id, date_id, time_id, location_id);
EOF
}

# ------------------------------------------------------------------------------- #

for dbase in $dbases; do
    if  [[ ! -f $dbase || ! -r $dbase ]]; then
        echo "Database file $dbase does not exists or is not readable."
        echo "Exiting"
        exit 1
    fi
done

for dbase in $dbases; do
    echo "Generating indexes for queries in database ${dbase}"
    create_indices ${dbase}
done
