#!/bin/bash
# Cumulative TESS data bulk dump since the beginning of the project in IDA format
# This is meant to be invoked manually, not a from cron file

# ------------------------------------------------------------------------------
#                             AUXILIARY FUNCTIONS
# ------------------------------------------------------------------------------


help() {
    name=$(basename ${0%.sh})
    echo "Usage:"
    echo "$name -d <database path> -o <dst dir> -m <YYYY-MM> -l <log file path prefix>"
    echo "Defaults to:"
    echo "name -d $DEFAULT_DATABASE -o $DEFAULT_DST_DIR -m $DEFAULT_MONTH -l $DEFAULT_LOG_FILE_PREFIX"
}


query_names() {
dbase=$1
sqlite3 ${dbase} <<EOF
SELECT name 
FROM tess_v 
WHERE name like 'stars%' 
AND valid_state = 'Current' 
ORDER by CAST(substr(name, 6) as decimal) ASC;
EOF
}

# ------------------------------------------------------------------------------- #

DEFAULT_DATABASE="/var/dbase/tess.db"
DEFAULT_DST_DIR="/var/dbase/reports/IDA"
DEFAULT_MONTH="2015-01"
DEFAULT_LOG_FILE_PREFIX=/var/log/ida_all

TEE=$(which tee)
TESS_IDA=$(which tess-ida)
LOG_DATE=$(/usr/bin/date +%Y%m%d)


dbase="${DEFAULT_DATABASE}"
out_dir="${DEFAULT_DST_DIR}"
month="${DEFAULT_MONTH}"
log_file="${DEFAULT_LOG_FILE_PREFIX}_${LOG_DATE}.log"

while getopts ":hd:o:m:l:" opt; do
    case ${opt} in
    d)
        dbase="${OPTARG}"
        ;;
    o)
        out_dir="${OPTARG}"
        ;;
    m)
        month="${OPTARG}"
        ;;
    l)
        log_file="${OPTARG}_${LOG_DATE}.log"
        ;;
    h)
        help
        exit 0
        ;;
    :)
        echo "Option -${OPTARG} requires an argument."
        exit 1
        ;;
    ?)
        echo "Invalid option: -${OPTARG}."
        exit 1
        ;;
  esac
done
shift "$((OPTIND-1))"


if  [[ ! -f $dbase || ! -r $dbase ]]; then
        echo "[WARNING] Database file $dbase does not exists or is not readable. Aborting..." | ${TEE} -a ${log_file}
        exit 1
fi


if  [[ -f /etc/cron.d/tessdb_remote_backup ]]; then
        echo "[WARNING] tess.db remote  backup is active. Aborting..." | ${TEE} -a ${log_file}
        exit 1
fi


if  [[ -f /etc/cron.d/webdav_ida_rclone ]]; then
        echo "[WARNING] IDA WebDAV sync is active. Aborting..." | ${TEE} -a ${log_file}
        exit 1
fi

if  [[ -d ${out_dir} ]]; then
        echo "[INFO] Purge previous IDA reports directory..." | ${TEE} -a ${log_file}
        rm -fr ${out_dir}
        mkdir -p ${out_dir}
fi

photometers=$(query_names ${dbase})
# Loops over the instruments file and dumping data
for instrument in $photometers; do
    echo "[INFO] Generating IDA file for TESS $instrument for ${START_DATE} under ${out_dir}/${instrument}" | ${TEE} -a ${log_file}
    ${TESS_IDA} ${instrument} --console --log-file ${log_file} --from-month ${month} -d ${dbase} -o ${out_dir}
done

echo "FINALIZED ALL BULK DUMP !!!!" | ${TEE} -a ${log_file}
