#!/bin/bash
DATABASE="/home/rafa/tessdb-operations/dbase/tess.db-20231026"
if ! test -d processed; then
  mkdir processed
fi

for FILE in $(ls -1 *.sql)
do
	echo "sqlite3 $DATABASE < $FILE"
	/usr/bin/time --format='%C took %e seconds' sqlite3 $DATABASE < $FILE
	mv $FILE processed
	exit 0 # Yes ! we will do it one at a time since it takes so much ...
done
