#!/bin/bash
DATABASE=${1:-/var/dbase/tess.db}
SECS=3
if ! test -d processed; then
  mkdir processed
fi

for FILE in $(ls -1 *.sql)
do
	echo "sqlite3 $DATABASE < $FILE"
	/usr/bin/time --format='%C took %e seconds' sqlite3 $DATABASE < $FILE
	mv $FILE processed
	echo "sleeping for $SECS seconds so that we can abort with <CTRL-C>"
	sleep $SECS
	#exit 0 # Yes ! we will do it one at a time since it takes so much ...
done
