#!/bin/bash
DATABASE=${1:-/var/dbase/tess.db}
SECS=3

echo "Creating SQLite Index tess_id_readings_i on Database ${DATABASE} table tess_readings_t"
sqlite3 ${DATABASE} <<EOF
	CREATE INDEX IF NOT EXISTS tess_id_readings_i ON tess_readings_t(tess_id);
EOF


if ! test -d processed; then
  mkdir processed
fi

for FILE in $(ls -1 *.sql)
do
	echo "sqlite3 $DATABASE < $FILE"
	/usr/bin/time --format='%C took %e seconds' sqlite3 $DATABASE < $FILE
	mv $FILE processed
	echo "sleeping for $SECS seconds so that we can abort with <CTRL-C>"
	sleep $SECS
	#exit 0 # Yes ! we will do it one at a time since it takes so much ...
done

echo "Deleting SQLite Index tess_id_readings_i on Database ${DATABASE}"
sqlite3 ${DATABASE} <<EOF
	DROP INDEX IF EXISTS tess_id_readings_i;
EOF

echo "Compacting database ${DATABASE}"
sqlite3 ${DATABASE} <<EOF
	VACUUM;
EOF
