#!/bin/bash
# ----------------------------------------------------------------------
# Copyright (c) 2023 Rafael Gonzalez.
#
# See the LICENSE file for details
# ----------------------------------------------------------------------
python -m tessutils "$@"
